// packages/vue/lib/form-builder/FormBuilder.vue
<template>
  <div
    :id="DIV_ID"
    ref="containerRef"
    :style="{
      height: `${height}px`,
      width: '100%',
      overflow: 'hidden',
    }"
  />
</template>

<script lang="ts">
import { defineComponent, onMounted, onUnmounted, ref, watch } from 'vue';
import { BuilderExternal, type FormSchema } from '@efie-form/core';

const DIV_ID = 'efie-form-builder';

export default defineComponent({
  name: 'FormBuilder',
  props: {
    height: {
      type: Number,
      required: true,
    },
    options: {
      type: Object,
      default: () => ({}),
    },
    onReady: {
      type: Function,
      default: () => {},
    },
  },
  setup(props, { expose }) {
    const containerRef = ref<HTMLDivElement | null>(null);
    const builderRef = ref<BuilderExternal | null>(null);

    onMounted(() => {
      if (containerRef.value && !builderRef.value) {
        builderRef.value = new BuilderExternal({
          id: DIV_ID,
          onReady: () => {
            props.onReady?.();
          },
        });
      }
    });

    onUnmounted(() => {
      if (builderRef.value) {
        const container = document.getElementById(DIV_ID);
        if (container) {
          container.innerHTML = '';
        }
        builderRef.value = null;
      }
    });

    watch(
      () => props.height,
      (newHeight) => {
        if (builderRef.value) {
          builderRef.value.setHeight(newHeight);
        }
      }
    );

    // Expose methods to parent component
    expose({
      loadSchema: (schema: FormSchema) => {
        builderRef.value?.loadSchema(schema);
      },
      getSchema: () => {
        return builderRef.value?.getValue() as FormSchema;
      },
    });

    return {
      containerRef,
      DIV_ID,
    };
  },
});
</script>

// packages/react/lib/form-builder/form-builder.tsx
import { type CustomInputDef, type FormSchema, Iframe } from '@efie-form/core';
import type { RefObject } from 'react';
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';

const DIV_ID = 'efie-form-builder';

interface FormBuilderProps {
  ref: RefObject<FormBuilderRef>;
  height: number;
  formInputs?: CustomInputDef[];
  schema?: FormSchema;
  formKeyNonEditable?: boolean;
  inputNonReusable?: boolean;
  maxHistories?: number;
}

export interface FormBuilderRef {
  getSchema: () => FormSchema;
}

const FormBuilder = forwardRef<FormBuilderRef, FormBuilderProps>(
  ({ height, formInputs, schema, formKeyNonEditable, inputNonReusable, maxHistories }, ref) => {
    const builderRef = useRef<Iframe | undefined>();
    const containerRef = useRef<HTMLDivElement>(null);

    // Initialize Iframe once
    useEffect(() => {
      // Only create new instance if one doesn't exist
      if (!builderRef.current && containerRef.current) {
        builderRef.current = new Iframe({
          id: DIV_ID,
          formInputs,
          height,
          schema,
          formKeyNonEditable,
          inputNonReusable,
          maxHistories,
        });
      }

      // Cleanup only when component unmounts
      return () => {
        if (builderRef.current) {
          // Clean up the iframe
          const container = document.querySelector(`#${DIV_ID}`);
          if (container) {
            container.innerHTML = '';
          }
          builderRef.current = undefined;
        }
      };
    }, [formInputs, height, schema, formKeyNonEditable, inputNonReusable, maxHistories]);

    // Update height when prop changes
    useEffect(() => {
      if (builderRef.current) {
        builderRef.current.setHeight(height);
      }
    }, [height]);

    // Expose methods via ref
    useImperativeHandle(
      ref,
      () => ({
        getSchema: () => {
          return builderRef.current?.getValue() as FormSchema;
        },
      }),
      [],
    );

    useEffect(() => {
      if (!builderRef.current || !formInputs) return;
      builderRef.current.setFormInputs(formInputs);
    }, [formInputs]);

    return (
      <div
        ref={containerRef}
        id={DIV_ID}
        style={{
          height: `${height}px`,
          width: '100%',
          overflow: 'hidden',
        }}
      />
    );
  },
);

export default FormBuilder;
