// demo/react/builder/src/app.tsx
import type { FormBuilderRef } from '@efie-form/react';
import { FieldType, FormBuilder } from '@efie-form/react';
import { useEffect, useRef, useState } from 'react';
import { schema } from './schema';

function App() {
  const formBuilderRef = useRef<FormBuilderRef>(null);
  const [height, setHeight] = useState(window.innerHeight);

  useEffect(() => {
    let resizeTimeout: number;
    const handleResize = () => {
      clearTimeout(resizeTimeout);
      resizeTimeout = setTimeout(() => {
        setHeight(window.innerHeight);
      }, 100);
    };

    handleResize();
    window.addEventListener('resize', handleResize);

    return () => {
      clearTimeout(resizeTimeout);
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  return (
    <div>
      <FormBuilder
        ref={formBuilderRef}
        height={height}
        schema={schema}
        inputNonReusable
        maxHistories={25}
        formInputs={[
          {
            id: 'long_text',
            label: 'Short Text',
            type: FieldType.SHORT_TEXT,
          },
          {
            id: 'multiple_choices',
            label: 'Long Text',
            type: FieldType.LONG_TEXT,
          },
          {
            id: 'fd123',
            label: 'Number',
            type: FieldType.NUMBER,
          },
        ]}
      />
    </div>
  );
}

export default App;

// demo/vue/builder/src/app.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { FormBuilder } from '@efie-form/vue';
import { schema } from './schema';

const formBuilderRef = ref<InstanceType<typeof FormBuilder> | null>(null);
const height = ref(window.innerHeight);

let resizeTimeout: NodeJS.Timeout;
const handleResize = () => {
  clearTimeout(resizeTimeout);
  resizeTimeout = setTimeout(() => {
    height.value = window.innerHeight;
  }, 100);
};

const handleReady = () => {
  formBuilderRef.value?.loadSchema(schema);
};

onMounted(() => {
  handleResize();
  window.addEventListener('resize', handleResize);
});

onUnmounted(() => {
  clearTimeout(resizeTimeout);
  window.removeEventListener('resize', handleResize);
});
</script>

<template>
  <FormBuilder ref="formBuilderRef" :height="height" :onReady="handleReady" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
