// packages/react/lib/form-builder/FormBuilder.tsx
import type { RefObject } from 'react';
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
} from 'react';
import { type FormSchema, BuilderExternal } from '@efie-form/core';

const DIV_ID = 'efie-form-builder';

interface FormBuilderProps {
  ref: RefObject<FormBuilderRef>;
  options?: FormBuilderOptions;
  onReady?: () => void;
  height: number;
}

interface FormBuilderOptions {
  inputFields?: string[];
  hiddenFields?: string[];
}

export interface FormBuilderRef {
  loadSchema: (schema: FormSchema) => void;
  getSchema: () => FormSchema;
}

const FormBuilder = forwardRef<FormBuilderRef, FormBuilderProps>(
  ({ onReady, height }, ref) => {
    const builderRef = useRef<BuilderExternal | undefined>();
    const containerRef = useRef<HTMLDivElement>(null);

    // Initialize BuilderExternal once
    useEffect(() => {
      // Only create new instance if one doesn't exist
      if (!builderRef.current && containerRef.current) {
        builderRef.current = new BuilderExternal({
          id: DIV_ID,
          onReady: () => {
            onReady?.();
          },
        });
      }

      // Cleanup only when component unmounts
      return () => {
        if (builderRef.current) {
          // Clean up the iframe
          const container = document.querySelector(`#${DIV_ID}`);
          if (container) {
            container.innerHTML = '';
          }
          builderRef.current = undefined;
        }
      };
    }, [onReady]); // Empty dependency array to run only once

    // Update height when prop changes
    useEffect(() => {
      if (builderRef.current) {
        builderRef.current.setHeight(height);
      }
    }, [height]);

    // Expose methods via ref
    useImperativeHandle(
      ref,
      () => ({
        loadSchema: (schema: FormSchema) => {
          builderRef.current?.loadSchema(schema);
        },
        getSchema: () => {
          return builderRef.current?.getValue() as FormSchema;
        },
      }),
      []
    );

    return (
      <div
        ref={containerRef}
        id={DIV_ID}
        style={{
          height: `${height}px`,
          width: '100%',
          overflow: 'hidden',
        }}
      />
    );
  }
);

export default FormBuilder;

// packages/vue/lib/form-builder/FormBuilder.vue
<template>
  <div
    :id="DIV_ID"
    ref="containerRef"
    :style="{
      height: `${height}px`,
      width: '100%',
      overflow: 'hidden',
    }"
  />
</template>

<script lang="ts">
import { defineComponent, onMounted, onUnmounted, ref, watch } from 'vue';
import { BuilderExternal, type FormSchema } from '@efie-form/core';

const DIV_ID = 'efie-form-builder';

export default defineComponent({
  name: 'FormBuilder',
  props: {
    height: {
      type: Number,
      required: true,
    },
    options: {
      type: Object,
      default: () => ({}),
    },
    onReady: {
      type: Function,
      default: () => {},
    },
  },
  setup(props, { expose }) {
    const containerRef = ref<HTMLDivElement | null>(null);
    const builderRef = ref<BuilderExternal | null>(null);

    onMounted(() => {
      if (containerRef.value && !builderRef.value) {
        builderRef.value = new BuilderExternal({
          id: DIV_ID,
          onReady: () => {
            props.onReady?.();
          },
        });
      }
    });

    onUnmounted(() => {
      if (builderRef.value) {
        const container = document.getElementById(DIV_ID);
        if (container) {
          container.innerHTML = '';
        }
        builderRef.value = null;
      }
    });

    watch(
      () => props.height,
      (newHeight) => {
        if (builderRef.value) {
          builderRef.value.setHeight(newHeight);
        }
      }
    );

    // Expose methods to parent component
    expose({
      loadSchema: (schema: FormSchema) => {
        builderRef.value?.loadSchema(schema);
      },
      getSchema: () => {
        return builderRef.value?.getValue() as FormSchema;
      },
    });

    return {
      containerRef,
      DIV_ID,
    };
  },
});
</script>
